n1=float(input("ingresar la primera nota: "))
n2=float(input("ingrese la segunda nota : "))
n3=float(input("ingresar la tercera nota: "))
n4=float(input("ingrese la cuarta nota: "))
n5=float(input("ingresar la quinta nota: "))
prom=((n1*0.15)+(n2*0.2)+(n4*0.3)+(n3*0.15)+(n5*0.2))
print("su promedio es: ",prom)